### ISSUE TITLE
wrong posts tags

### ISSUE THREAD

**Issue by RadikKurmanaev** [guyromellemagayano/gatsby-source-bigcommerce-v2#95]
Hi. I noticed that there is a bug in creating nodes for the Blog Tags Endpoint ( /v2/blog/tags). My test store has four tags, but only the last one is displayed in gatsby graphql. I think the error is in the handleCreateNodeFromData method in generating the id for the node. You use ['id: createNodeId(`${nodeType}-${item.id}`)' ](https://github.com/Epic-Design-Labs/gatsby-source-bigcommerce/blob/7767c600783daef09bbeb0900c4bf488c53d59d9/src/gatsby-node.js#L24)but the returned tag object does not have an id field and so all nodes generate the same gatsby id and because of that they replace each other.
Possible Solution:
'id: createNodeId(`${nodeType}-**${item.id || item.tag}**`)' or better yet use uuid for unique id's (https://github.com/uuidjs/uuid)
![image](https://user-images.githubusercontent.com/94942993/210149747-e2aee02b-eb73-4cc7-97a4-11eadeb47b84.png)

**Comment by guyromellemagayano** [comment]
Hey @RadikKurmanaev . Im looking to upgrade the package with newer features like data build caching among other common plugin features. In the meantime, I will take note of this and will roll out a fix soon. Happy New Year to you sir. Thanks for using our plugin. Cheers 🎉🍾

**Comment by RadikKurmanaev** [comment]
thank you, happy new year to you too:)

**Comment by guyromellemagayano** [comment]
@RadikKurmanaev Hey there. I just released a new plugin version that will resolve your issue while also featuring new plugin options as well. Head over here for more info: https://www.npmjs.com/package/@epicdesignlabs/gatsby-source-bigcommerce. 

Cheers! 🥂
